workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' # i hate merge request pipelines
      when: never
    - when: always

stages:
  - build
  - test

build:
  image: registry.gitlab.com/pagekeytech/pkos:latest
  stage: build
  script:
    - scripts/os.py build
  artifacts:
    paths:
      - dist/*

test:
  image: registry.gitlab.com/pagekeytech/pkos:latest
  stage: test
  needs:
    - build
  script:
    - ./scripts/os.py test
  artifacts:
    paths:
      - public/
